import React, { useState, useEffect } from 'react'
import { Card, Loader, FormField } from '../components'

const RenderCards = ({ data, title }) => {
    if (data?.length > 0) {
        return data.map((post) => <Card key={post._id} {...post} />)
    }
    return (
        <h2 className='mt-5 font-bold text-blue-600 text-xl uppercase'> {title}</h2>
    )
}

const Home = () => {
    const [loading, setLoading] = useState(false);
    const [allPosts, setAllposts] = useState(null);
    const [searchText, setSearchText] = useState('')

    return (
        <section className='max-w-7xl mx-auto'>
            <div>
                <h1 className='font-extrabold text-gray-800 text-[32px] '>The Community Showcase</h1>
                <p className='mt-2 text-gray-500 text-[18px] max-w-[500px]'>Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
            </div>

            <div className='mt-16 '>
                <FormField></FormField>
            </div>

            <div className='mt-10'>
                {loading ?
                    (<div className='flex justify-center items-center'><Loader /></div>)
                    :
                    (<>
                        {searchText && (<h2 className='font-medium text-xl text-stone-500 mb-3' >
                            Searching results for
                            <span className='text-slate-800'>
                                {searchText}
                            </span>
                        </h2>
                        )}
                        <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 gap-3'>
                            {searchText ?
                                (<RenderCards
                                    data={[]}
                                    title="No Search results found"
                                />) :
                                (<RenderCards
                                    data={[]}
                                    title="No POST found"
                                />)
                            }
                        </div>
                    </>
                    )}
            </div>
        </section>
    )
}

export default Home